# .github/workflows/terraform-ci.yml
name: Terraform CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.8.5

      - name: Run Composite Terraform Validation
        uses: ./.github/actions/terraform-check
        with:
          working-directory: .

      - name: Terraform Plan Test
        run: |
          terraform plan -input=false

        
      - name: variable test
        run: |
          echo "X=1" >> $GITHUB_ENV
          echo $X
          echo "$GITHUB_ENV"

      - name: variable test2
        run: |
          echo $X
          echo "$GITHUB_ENV"
      - name: Print Event File Path
        run: echo "$GITHUB_EVENT_PATH"
     
      - name: Show Payload
        run: cat "$GITHUB_EVENT_PATH"